name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
                    - name: CodeQL Bundle
  # You may pin to the exact commit or the version.
  # uses: advanced-security/codeql-bundle-action@9437ba7f33c2a978c8897fb21b2a7e0809199d20
  uses: advanced-security/codeql-bundle-action@v1.1.0
  with:
    # The tag of bundle release to customize (e.g., codeql-bundle-20220311)
    bundle-version: # optional, default is latest
    # A comma-separated list of CodeQL packs to include in the bundle
    packs: 
    # Root directory where the codeql-workspace.yml file is located
    workspace: # optional, default is .
    # Upload the created bundle
    upload: # optional, default is true
    # 
    token: # optional, default is ${{ github.token }}
    # The max number of packs that will be processed concurrently
    concurrency-limit: # optional, default is 2
          
